info:
  version: '@project.version@'
  stage: dev

server:
  port: '@server.port@'

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true

management:
  server:
    port: '@management.port@'
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      application: proxy-mocket-inspector
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
